### ISSUE TITLE
Creation of RESTful API FOR items

### ISSUE THREAD

**Issue by neelamnagarajgithub** [mohitparmar1/Shopy#19]
as of know there is the data in the json file itself. by using the MVC architecture , i can create a restful api route which serves the frontend and connect the api to frontend.

please assign me this issue under GSSOC24

**Comment by niteshtiwari52** [comment]
@neelamnagarajgithub 
You will make routes only for items of anything else. 

Could you please mentioned clearly that what routes you are going implement along the with basic setup of the backend. 
Because there are a lot of API you have to make. If you can mentioned clearly then I can also proceed with backend others routes. 
Please consider it as soon as possible.

**Comment by neelamnagarajgithub** [comment]
I am going to implement three routes
./api/v1/womens
/api/v1/kids
/api/v1/mens

**Comment by niteshtiwari52** [comment]
@neelamnagarajgithub Alright. Thanks for for the clarification. 

@mohitparmar1 As #19 will deal with the products and i will implement the login and sign up with OTP functionality. 
Now could you assign me the issue #31

**Comment by Ayush-may** [comment]
@neelamnagarajgithub Hii , can u pls explain me how did u add mongo in other application.
I mean u create the server from your account but how u can set it on other's project , can we do this ?

and how did u manage ur all secrets keys ?
I dont know about this things , thats y i want to learn something from u .

Thank u :smile:  !

**Comment by niteshtiwari52** [comment]
@Ayush-may 
I am trying to explain, 

For using mongoDB into our application we have to use a database connection link called MONGO_URI Or MONGO_URL. 

We can get the MONGO_URI from the mongodb Atlas and you can use database by the connection url. 

Apart from the atlas you can use mongodb compass as well. 

Now your 2nd Question was that how to manage all secret?? 

For keeping all sensitive data such as Database url, jwt secret api key, etc . We have to keep all these things into our  .env file .
For the security purpose we do not commit on GitHub. Because it contains some sensitive data. So it will present locally to run the application in development environment. 
But after deploying we pass all the environment to the application by entering all the sensitive keys and data as environment variables.

I hope you are able to understand little bit. 

If any face any issues and help need, feel free to ask.

**Comment by niteshtiwari52** [comment]
@mohitparmar1 i request you to please create a particular project specific channel under GSSOC 2024 to discuss in efficient manner.

**Comment by mohitparmar1** [comment]
@niteshtiwari52 , your suggestions would be appreciated.
