### ISSUE TITLE
 Improve README.md for Better Project Understanding

### ISSUE THREAD

**Issue by saikuladeepgithub** [mohitparmar1/Shopy#86]
The current README.md provides basic setup instructions for the Shopy project. However, it can be improved to provide a more comprehensive overview of the project, its features, and how to contribute effectively.
The enhanced README should include:
A brief introduction to the project and its purpose.
A detailed description of the project's features and functionality.
Clear setup instructions with any prerequisites.
Contribution guidelines, including how to submit pull requests and raise issues.
Contact information or links to community resources for further support.
This improvement will make it easier for new contributors to understand the project and get involved.

**Comment by saikuladeepgithub** [comment]
I want to contribute it as a gssoc contributor,could you please assign it to me

**Comment by aasthakourav20** [comment]
What lacks in this repository :  
Hey @mohitparmar1 , a README file is essential in any given repository because it serves as the primary source of information about the project. It provides an overview of the project's purpose, how to install and use it, and any necessary prerequisites. Additionally, the README often includes guidelines for contributing, links to documentation, and contact information for the maintainers.  By consolidating all critical information in one place, a README file significantly improves the user experience and facilitates effective project management. 
So I would like to add aesthetics to the readme file , Kindly assign this task to me .

**Comment by mohitparmar1** [comment]
issue has been resolved!
